#!/bin/sh

set -e

error() {
    printf "prtlbx: %s\n" "$@" 1>&2
    exit 1
}

pkg_query() {
    sed -n '/^'"$1"'$/,/^$/p' "${pkgdb}" | grep -v '^$'
}

pkg_check() {
    pkg_query "$1" >/dev/null 2>&1
}

pkg_version() {
    pkg_query "$1" | sed -n '2p' | grep .
}

pkg_files() {
    pkg_query "$1" | tail -n+3 | grep .
}

pkg_list() {
    if [ -n "$1" ] && [ "$1" != "*" ]; then
        error "option -l with -i does not accept an argument"
    fi
    awk -v o=1 '/^$/{o=0}{if(o++==1)print}' "${pkgdb}"
}

prt_usable() {
    if ! [ -d "$(sh -c 'echo $1' -- "$ports"/*)" ]; then
        error "no port directories present in $ports"
    fi
}

pkg_usable() {
    if ! [ -f "$pkgdb" ]; then
        error "no package database present at $pkgdb"
    fi
}

prt_path() {
    if echo "$1" | grep -q ".*/.*"; then
        path="${ports}${1}"
    else
        path="${ports}*/${1}"
    fi
    find "${ports}" -mindepth 2 -maxdepth 2 -type d -path "$path" -print -quit  | grep .
}

prt_check() {
    prt_path "$1" >/dev/null 2>&1
}

prt_version() {
    pkgfile="$(prt_path "$1")/Pkgfile"
    awk -F= '/^ *version=/{v=$2}/^ *release=/{r=$2}END{print v "-" r}' "$pkgfile"
}

prt_footprint() {
    footprint="$(prt_path "$1")/.footprint"
    cat "$footprint"
}

pkg_footprint() {
    files="$(pkg_files $1)"
    env -C / stat -c "%A %U/%G %N" $files | while read -r line; do
        echo "$line" | xargs printf "%-15s %-15s %s %s %s\n"
    done
}

prt_files() {
    prt_footprint "$1" | awk '{print $3}'
}

prt_list() {
    if echo "$1" | grep -q ".*/.*"; then
        path="${1}"
    else
        path="${1}/*"
    fi
    find "${ports}" \
        -mindepth 2 -maxdepth 2 -type d \
        -path "${ports}${path}" -printf "%P\n" \
       | cut -d'/' -f2 \
       | grep "."
}

foreach() {
    fn="$1"
    shift
    for arg in "$@"; do
        $fn "$arg"
    done
}


prt_deps() {
    pkgfile="$(prt_path "$1")/Pkgfile"
    rawdeps="$(sed -n 's/^# Depends on: //p' "$pkgfile")"
    printf "%s\n" "$1" $rawdeps 
}

argstr() {
    echo "$*"
}

depmerge() {
    printf "%s\n" "$@" $(foreach prt_deps "$@") \
        | sort \
        | uniq \
        | { tee /dev/fd/3 \
          | [ "$(argstr $(cat -))" != "$*" ]; \
          } 3>&1

}

prt_alldeps() {
    if merged="$(depmerge "$@")"; then
        prt_alldeps $merged
    else
        prt_check $merged
        printf "%s\n" $merged
    fi
}

min() {
    [ "$1" -lt "$2" ] && echo "$1" || echo "$2"
}

checkarg() {
    if [ $# -lt $(( $1 + 3 )) ]; then
        error "option $3 requires at least $1 arguments"
    fi

    shift="$(min "$(( $# - 2 ))" "$(( $2 + 1 ))")"
}

checkerr() {
    if ! "$@"; then
        error "fail: $*"
    fi
}

setquery() {
    if [ -n "$query" ]; then
        error "query already set to '$query', can't change to '$1'"
    fi

    query="$1"
}

wasseen() {
    if [ -z "$seen" ]; then
        seen="$1"
        return 1
    fi

    [ "$seen" = "$1" ]
}

splitopt() {
    echo "$1" \
        | cut -c2- \
        | sed 's/\(.\)/-\1 /g' \
        | { tee /dev/fd/3 \
          | shift="$(awk '{print NF}')"; \
          } 3>&1
}

wrap() {
    retcode=1
    if out="$( "$@" )"; then
        retcode=0
    fi
    shift

    if [ $retcode = $negate ]; then
        if [ $more = 1 ]; then
            printf "$* %s\n" $out
        elif [ -n "$out" ]; then
            printf "%s\n" "$out"
        fi
    elif [ $noexit = 1 ]; then
        lasterr=1
    else
        exit 1
    fi
}

help() {
    echo "usage: $1 [<opt>] <tgt> <qry> [<arg>...]"
    echo "  options:"
    echo "    -r,  --root <path>          set alternate filesystem root"
    echo "    -x,  --noexit               do not exit on first failure"
    echo "    -m,  --more                 append to the input instead of replacing it"
    echo "    -n,  --negate               negate the output"
    echo "  targets:"
    echo "    -s,  --source               operate on source ports"
    echo "    -i,  --installed            operate on installed ports"
    echo "  universal queries:"
    echo "    -v,  --version <prt>...     print the port version"
    echo "    -f,  --files <prt>...       print the port files"
    echo "    -t,  --footprint <prt>...   print the port footprint"
    echo "    -c,  --check <prt>...       check if the port exists"
    echo "    -l,  --list                 print all present ports"
    echo "    -h,  --help                 print help"
    echo "  source queries:"
    echo "    -p,  --path <prt>...        print path to the port"
    echo "    -d,  --deps <prt>...        print direct port dependecies"
    echo "    -a,  --alldeps <prt>...     print all port dependecies"
    echo "    -l,  --list <col>           print all present ports from collection <col>, can glob"
}

root="/"
noexit=0
more=0
negate=0
stdin=0
seen=""
query=""
target=""
lasterr=0

while :; do
    case $1 in
        -r|--root)      checkarg 1 1 "$@";
                        root="$(checkerr readlink -f "$2")/";
                        shift $shift ;;
        -s|--source)    target=s;           shift ;;
        -i|--installed) target=i;           shift ;;
        -m|--more)      more=1;             shift ;;
        -n|--negate)    negate=1;           shift ;;
        -x|--noexit)    noexit=1;           shift ;;
        -)              stdin=1;            shift ;;
        -v|--version)   setquery version;   shift ;;
        -f|--files)     setquery files;     shift ;;
        -t|--footprint) setquery footprint; shift ;;
        -l|--list)      setquery list;      shift ;;
        -p|--path)      setquery path;      shift ;;
        -c|--check)     setquery check;     shift ;;
        -d|--deps)      setquery deps;      shift ;;
        -a|--alldeps)   setquery alldeps;   shift ;;
        -h|--help)      help "$0"; exit 0; ;;
        -?|--*)         error "unknown option '$1', see $0 --help" ;;
        -*)             splat="$(splitopt "$1")"; shift $shift; set -- $splat "$@";;
        '')             break; ;;
        *)              wasseen "$1" && break || set -- "$@" "$1" && shift ;;
    esac
done

if [ -z "$query" ]; then
    error "no query selected, see $0 --help"
fi

if [ -z "$target" ]; then
    error "no target selected, see $0 --help"
fi

[ $target = s ] && prefix=prt || prefix=pkg

if ! type ${prefix}_${query} >/dev/null 2>&1; then
    error "query '${query}' is not supported with target '$target', see $0 --help"
fi

if [ $query = "list" ] && [ $# -eq 0 ]; then
    set -- "*"
fi

ports="${root}usr/ports/"
pkgdb="${root}var/lib/pkg/db"

${prefix}_usable

foreach "wrap ${prefix}_${query}" "$@"

if [ $# = 0 ] || [ $stdin = 1 ]; then
    while read -r arg; do
        wrap ${prefix}_${query} $arg
    done
fi

exit $lasterr
